services:
    pg-database:
        image: postgres:13
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=ny_taxi
        ports:
            - 5431:5432
        volumes:
            - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    
    # data-pipeline:
    #     build: .
    #     depends_on:
    #         - pg-database
        

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 9090:80
        depends_on:
            - pg-database

